version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: anpr-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

  redis:
    image: redis:7-alpine
    container_name: anpr-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    container_name: anpr-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/anpr?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-jwt-key-change-this
      - PORT=5000
      - FRONTEND_URL=http://localhost:5000
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs

volumes:
  mongodb_data:
  redis_data:
