version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: anpr-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: anpr
    networks:
      - anpr-network

  redis:
    image: redis:7-alpine
    container_name: anpr-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - anpr-network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: anpr-backend
    restart: unless-stopped
    ports:
      - "6001:6001"
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/anpr?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - PORT=6001
      - FRONTEND_URL=http://localhost:6000
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./backend/python/models:/app/python/models
    networks:
      - anpr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: anpr-frontend
    restart: unless-stopped
    ports:
      - "6000:6000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:6001/api
      - VITE_SOCKET_URL=http://localhost:6001
    networks:
      - anpr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: anpr-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/var/www/uploads:ro
    depends_on:
      - frontend
      - backend
    networks:
      - anpr-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  anpr-network:
    driver: bridge
